export enum PokemonType {
  Grass = 'Grass',
  Poison = 'Poison',
  Fire = 'Fire',
  Flying = 'Flying',
  Water = 'Water',
  Normal = 'Normal',
  Fairy = 'Fairy',
  Ground = 'Ground',
  Rock = 'Rock',
  Fighting = 'Fighting',
  Electrik = 'Electrik',
  Ice = 'Ice',
  Dragon = 'Dragon',
  Dark = 'Dark',
  Ghost = 'Ghost',
  Psychic = 'Psychic',
  Bug = 'Bug',
  Steel = 'Steel',
}
